#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/sphinxsearch" ] && [ ! -L "/etc/init.d/sphinxsearch" ]; then
		if [ "`md5sum \"/etc/init.d/sphinxsearch\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' sphinxsearch | sed -n -e \"\\\\' /etc/init.d/sphinxsearch '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/sphinxsearch has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/sphinxsearch" "/etc/init.d/sphinxsearch.dpkg-bak"
		else
			rm -f "/etc/init.d/sphinxsearch"
		fi
	fi
fi
# End automatically added section
