development:
 enable_star: true
 morphology: stem_en
 html_strip: true
 min_infix_len: 3
 port: 9312
 sql_range_step: 10000000
 use_64_bit: true
 bin_path: /usr/local/bin
 searchd_binary_name: searchd
 indexer_binary_name: indexer

 production:
 enable_star: true
 morphology: stem_en
 html_strip: true
 min_infix_len: 3
 port: 9312
 sql_range_step: 10000000
 use_64_bit: true
 version: 1.10-beta
 min_prefix_len: 2
 bin_path: /usr/local/bin
 version: '1.10-beta'
 bin_path: /usr/local/bin
 searchd_binary_name: searchd
 indexer_binary_name: indexer
