development:
 enable_star: true
 morphology: stem_en
 html_strip: true
 min_infix_len: 3
 port: 9312
 sql_range_step: 10000000
 use_64_bit: true

# production:
# enable_star: true
# morphology: stem_en
# html_strip: true
# min_infix_len: 3
# port: 9312
# sql_range_step: 10000000
# use_64_bit: true
# version: 1.10-beta